// 検証用コメント。

// Phase A — pilots
import './badge.verify'
import './button.verify'
import './progress-bar.verify'
import './step-indicator.verify'
import './tabs.verify'

// 検証用コメント。
import './anki-flow-logo.verify'
import './card.verify'
import './empty-state.verify'
import './error-message.verify'
import './flow-tip.verify'
import './stat-card.verify'
import './toggle.verify'
import './toast.verify'
import './tag-input.verify'
import './filter-bar.verify'
import './data-table.verify'
import './modal.verify'
import './loading-overlay.verify'
import './form-field.verify'
import './language-picker.verify'
import './page-header.verify'
import './connected-badge.verify'
import './navigation-sidebar.verify'
import './app-shell.verify'
import './login-form.verify'

// Phase C — create/ + preview/ + history/
import './section-divider.verify'
import './smart-enrichment-banner.verify'
import './batch-item-list.verify'
import './language-selector.verify'
import './editable-field.verify'
import './additional-fields.verify'
import './collocation-editor.verify'
import './card-list.verify'
import './image-selector.verify'
import './card-preview.verify'
import './card-template-editor.verify'
import './audio-player.verify'
import './review-audio-players.verify'
import './history-table.verify'
import './history-content-type-filter.verify'
import './deck-selector.verify'
import './deck-creatable-field.verify'
import './category-selector.verify'
import './topic-selector.verify'
import './new-topic-modal.verify'
import './card-type-selector.verify'
import './language-form.verify'
import './it-form.verify'
import './general-form.verify'
import './configured-card-form.verify'
import './batch-preview-discard.verify'
import './preview-card-validation.verify'

// Phase D — admin/ managers + feature spec
import './category-manager.verify'
import './topic-manager.verify'
import './deck-manager.verify'
import './card-type-manager.verify'
import './content-type-manager.verify'
import './ai-output-profiles-editor.verify'
import './create-language-flow.verify'
import './create-content-types.verify'
import './resync-cards.verify'
import './study-language-settings.verify'
import './line-notification-settings.verify'
import './detected-language-modal.verify'
import './unsaved-changes-guard.verify'
