// Side-effect imports — mỗi spec tự đăng ký unit vào registry khi được import

// Phase A — pilots
import './badge.verify'
import './button.verify'
import './progress-bar.verify'
import './step-indicator.verify'
import './tabs.verify'

// Phase B — ui/ còn lại + layout
import './anki-flow-logo.verify'
import './card.verify'
import './empty-state.verify'
import './error-message.verify'
import './flow-tip.verify'
import './stat-card.verify'
import './toggle.verify'
import './tag-input.verify'
import './filter-bar.verify'
import './data-table.verify'
import './modal.verify'
import './loading-overlay.verify'
import './form-field.verify'
import './page-header.verify'
import './connected-badge.verify'
import './navigation-sidebar.verify'

// Phase C — create/ + preview/ + history/
import './section-divider.verify'
import './smart-enrichment-banner.verify'
import './language-selector.verify'
import './editable-field.verify'
import './collocation-editor.verify'
import './card-list.verify'
import './image-selector.verify'
import './card-preview.verify'
import './audio-player.verify'
import './history-table.verify'
import './word-detail-card.verify'
import './deck-selector.verify'
import './category-selector.verify'
import './topic-selector.verify'
import './card-type-selector.verify'
import './language-form.verify'
import './it-form.verify'
import './general-form.verify'

// Phase D — admin/ managers + feature spec
import './category-manager.verify'
import './topic-manager.verify'
import './deck-manager.verify'
import './card-type-manager.verify'
import './content-type-manager.verify'
import './create-language-flow.verify'
